name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  frontend-build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "24"

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      - name: Build project
        run: npm run build
        working-directory: ./frontend
      - name: Check for Debug statements  
        run: |
          if grep -R --include=\*.{js,jsx,ts,tsx} "console.log" ./frontend; then
            echo "❌ console.log statements found in frontend code!"
            exit 1
          else
            echo "✅ No console.log statements found in frontend."
          fi
      - name: check if build folder exists
        run: |
          if [ -d "frontend/dist" ]; then
              echo "Build folder exists."
          else
              echo "Build folder does not exist."
              exit 1
          fi

      - name: List build folder contents
        run: ls -la frontend/dist

      - name: Verify build output
        run: |
          if [ -f "frontend/dist/index.html" ]; then
              echo "Build output is valid."
          else
              echo "Build output is invalid."
              exit 1
          fi
  admin-build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "24"
      - name: Install dependencies
        run: npm install
        working-directory: ./admin-portal
      - name: Build project
        run: npm run build
        working-directory: ./admin-portal
      - name: Check for Debug statements
        run: |
          if grep -R --include=\*.{js,jsx,ts,tsx} "console.log" ./admin-portal; then
            echo "❌ console.log statements found in admin-portal code!"
            exit 1
          else
            echo "✅ No console.log statements found in admin-portal."
          fi
      - name: check if build folder exists
        run: |
          if [ -d "admin-portal/build" ]; then
              echo "Build folder exists."
          else
              echo "Build folder does not exist."
              exit 1
          fi
      - name: List build folder contents
        run: ls -la admin-portal/build
      - name: Verify build output
        run: |
          if [ -f "admin-portal/build/index.html" ]; then
              echo "Build output is valid."
          else
              echo "Build output is invalid."
              exit 1
          fi
